name: Latest LinkedIn Posts
on:
  schedule:
    - cron: '0 * * * *'  # Runs every hour
  workflow_dispatch:

jobs:
  update-readme:
    name: Update README with latest LinkedIn Posts
    runs-on: ubuntu-latest
    steps:
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: "https://www.linkedin.com/in/vishnu-s-0477ba246/detail/recent-activity/posts/"
